"""Public package surface for the nyc311 CLI and functional SDK."""

from __future__ import annotations

from ._version import version as __version__
from .cli import main
from .dataframes import (
    anomalies_to_dataframe,
    assignments_to_dataframe,
    coverage_to_dataframe,
    dataframe_to_records,
    gaps_to_dataframe,
    records_to_dataframe,
    summaries_to_dataframe,
)
from .exporters import (
    export_anomalies,
    export_geojson,
    export_report_card,
    export_service_requests_csv,
    export_topic_table,
)
from .geographies import (
    boundaries_to_dataframe,
    boundaries_to_geojson,
    clip_boundaries_to_bbox,
    list_boundary_layers,
    list_boundary_values,
    load_nyc_boundaries,
    load_nyc_council_districts,
    load_nyc_census_tracts,
    load_nyc_boundaries_geodataframe,
    load_nyc_neighborhood_tabulation_areas,
    load_sample_boundaries,
    load_sample_service_requests,
    spatially_enrich_records,
)
from .loaders import (
    REQUIRED_SERVICE_REQUEST_COLUMNS,
    load_boundaries,
    load_resolution_data,
    load_service_requests,
)
from .models import (
    BOROUGH_BRONX,
    BOROUGH_BROOKLYN,
    BOROUGH_MANHATTAN,
    BOROUGH_QUEENS,
    BOROUGH_STATEN_ISLAND,
    SUPPORTED_BOROUGHS,
    AnalysisWindow,
    AnomalyResult,
    BoundaryCollection,
    BoundaryFeature,
    BoundaryGeoJSONExport,
    ExportTarget,
    GeographyFilter,
    GeographyTopicSummary,
    ResolutionGapSummary,
    ServiceRequestFilter,
    ServiceRequestRecord,
    SocrataConfig,
    TopicAssignment,
    TopicCoverageReport,
    TopicQuery,
    normalize_borough_name,
    supported_topic_queries,
)
from .pipeline import fetch_service_requests, run_topic_pipeline
from .plotting import plot_boundary_choropleth, plot_boundary_preview
from .processors import (
    DEFAULT_TOPIC_RULES,
    aggregate_by_geography,
    analyze_resolution_gaps,
    analyze_topic_coverage,
    detect_anomalies,
    extract_topics,
    register_topic_rules,
)
from .spatial import (
    load_boundaries_geodataframe,
    records_to_geodataframe,
    spatial_join_records_to_boundaries,
    summaries_to_geodataframe,
)

__all__ = [
    "__version__",
    "AnalysisWindow",
    "AnomalyResult",
    "DEFAULT_TOPIC_RULES",
    "BOROUGH_BRONX",
    "BOROUGH_BROOKLYN",
    "BOROUGH_MANHATTAN",
    "BOROUGH_QUEENS",
    "BOROUGH_STATEN_ISLAND",
    "BoundaryCollection",
    "BoundaryFeature",
    "BoundaryGeoJSONExport",
    "ExportTarget",
    "GeographyFilter",
    "GeographyTopicSummary",
    "REQUIRED_SERVICE_REQUEST_COLUMNS",
    "ResolutionGapSummary",
    "SocrataConfig",
    "ServiceRequestFilter",
    "ServiceRequestRecord",
    "SUPPORTED_BOROUGHS",
    "TopicAssignment",
    "TopicCoverageReport",
    "TopicQuery",
    "aggregate_by_geography",
    "analyze_topic_coverage",
    "analyze_resolution_gaps",
    "anomalies_to_dataframe",
    "assignments_to_dataframe",
    "boundaries_to_dataframe",
    "boundaries_to_geojson",
    "clip_boundaries_to_bbox",
    "coverage_to_dataframe",
    "dataframe_to_records",
    "detect_anomalies",
    "export_anomalies",
    "export_geojson",
    "export_report_card",
    "export_service_requests_csv",
    "export_topic_table",
    "fetch_service_requests",
    "extract_topics",
    "gaps_to_dataframe",
    "list_boundary_layers",
    "list_boundary_values",
    "load_boundaries",
    "load_boundaries_geodataframe",
    "load_nyc_boundaries",
    "load_nyc_council_districts",
    "load_nyc_census_tracts",
    "load_nyc_boundaries_geodataframe",
    "load_nyc_neighborhood_tabulation_areas",
    "load_resolution_data",
    "load_sample_boundaries",
    "load_sample_service_requests",
    "load_service_requests",
    "main",
    "normalize_borough_name",
    "plot_boundary_choropleth",
    "plot_boundary_preview",
    "records_to_dataframe",
    "records_to_geodataframe",
    "register_topic_rules",
    "run_topic_pipeline",
    "spatially_enrich_records",
    "spatial_join_records_to_boundaries",
    "summaries_to_dataframe",
    "summaries_to_geodataframe",
    "supported_topic_queries",
]
