name: Compatibility

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * 1"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  FORCE_COLOR: 3

jobs:
  cross-platform-checks:
    name: Python ${{ matrix.python-version }} on ${{ matrix.runs-on }}
    runs-on: ${{ matrix.runs-on }}
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        include:
          - python-version: "3.13"
            runs-on: ubuntu-latest
          - python-version: "3.12"
            runs-on: windows-latest
          - python-version: "3.12"
            runs-on: macos-latest

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - uses: astral-sh/setup-uv@v7

      - name: Install package
        run: uv sync

      - name: Run tests
        run: uv run pytest -ra
